name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Run cargo fmt
        run: cargo fmt -- --check
      - name: Run cargo clippy
        run: cargo clippy -- -D warnings
      - name: Run tests
        run: cargo test --all --verbose
